### PR TITLE
Fix typo in hal/src/device.rs

### PR DESCRIPTION
**Pull request by Michael-Lfx**

### CODE REVIEW

**Comment by kvark** [comment]
Please squash everything.

> Existing reviewers: click here to make Michael-Lfx a reviewer

no idea why bors even wants this?

**Comment by grovesNL** [comment]
@Michael-Lfx only gfx reviewers can merge pull requests through bors unless permission is given explicitly

@kvark it’s because @Michael-Lfx tried to use “bors r+”

**Comment by Michael-Lfx** [comment]
just a little curious🤣

**Comment by Michael-Lfx** [comment]
I've updated it here:https://github.com/gfx-rs/gfx/pull/2244

**Comment by kvark** [comment]
@Michael-Lfx ftr, there is almost never a real need to open a new PR. You could have just force-pushed into this branch (`pr-branch-fixtypo`) and proceed with this one.

**Pull request closed without merging**
