### PR TITLE
Simplify target dependencies

### LINKED ISSUE #982: Simplify target dependencies
… in [Cargo.toml](https://github.com/gfx-rs/gfx/blob/master/Cargo.toml#L27-L37), it can be simplified as

```
[target.'cfg(unix)'.dependencies]
gfx_window_glfw = { path = "src/window/glfw", version = "0.10" }
gfx_window_sdl = { path = "src/window/sdl", version = "0.2" }

[target.'cfg(windows)'.dependencies]
gfx_device_dx11 = { path = "src/backend/dx11", version = "0.2" }
gfx_window_dxgi = { path = "src/window/dxgi", version = "0.2" }
```

[Manual](http://doc.crates.io/specifying-dependencies.html), available since Cargo 0.9.0 (Rust 1.8.0, which is stable month ago).

Just as suggestion.

### PR DESCRIPTION
**Pull request by eugene2k**
fixes #982

P.S. thx, pravic

### CODE REVIEW

**Comment by eugene2k** [comment]
On a similar note... what do you guys think of feature-gating sdl and glfw?

**Comment by kvark** [comment]
@eugene2k looks great, thanks!
Feature gating SDL and GLFW is the way to go. Would you want to implement it within this PR?

**Comment by eugene2k** [comment]
Might not need to feature-gate it at all. You said before that the reason why sdl was added as a dependency to gfx_app was so that everything could be tested with a single `cargo test`. That doesn't work anyway (see #961). So perhaps we should just remove sdl and glfw from gfx_app altogether.

**Comment by kvark** [comment]
The fact that this doesn't work is a bug (or missing feature) in cargo, not by design, IIRC. But I can't really see a use case where the app launcher would choose `sdl` or `glfw` over `glutin`, so your point still stands. I suppose we can remove `sdl` and `glfw` from `gfx_app` dependencies then, as you suggest.

**Comment by eugene2k** [comment]
There's a complication with that too. If the dependency is optional or not there, cargo can't find its manifest. So if you want to test say `gfx_window_sdl` you can't just run `cargo test -p gfx_window_sdl` in gfx root and have it tested. Instead you have to specify the manifest of the package (or `cd` to its directory) and then cargo will build not only the package itself, but also all of its dependencies even if you had already built them before, which will slow down travis/appveyor.

So, I guess you should probably merge the PR as it is...

**Comment by kvark** [comment]
Yeah, I've been worrying about this too. Let's leave this for now.
@homu r+

**Pull request merged**
