### PR TITLE
Fixed support for OpenGL drivers without VAO

### LINKED ISSUE #1319: SDL2 rendering: Error InvalidOperation executing command: BindVao
Hello,

I am trying to run icefoxen's [Triangle SDL](https://github.com/icefoxen/gfx/blob/master/examples/triangle-sdl/main.rs) example, with minor modifications to match the current release (here is the diff):
``` patch
47c47
<         gfx_window_sdl::init(&mut builder);
---
>         gfx_window_sdl::init::<ColorFormat, DepthFormat>(builder).unwrap();
50,51c50,52
<     let pso = factory.create_pipeline_simple(include_bytes!("shader/triangle_150.glslv"),
<                                 include_bytes!("shader/triangle_150.glslf"),
---
>     let pso = factory
>         .create_pipeline_simple(include_bytes!("shader/triangle_120.glslv"),
>                                 include_bytes!("shader/triangle_120.glslf"),

```

I am using SDL and I changed the shader version to 120 to be able to use GFX in WebGL. However, even when compiling to native (I'm on OS X), I get:

`thread 'main' panicked at 'Error InvalidOperation executing command: BindVao'`

which #1126 is supposed to solve.

Thank you for your help. If you wish maybe I can contribute something back like SDL or WebGL examples once I get this working.

### PR DESCRIPTION
**Pull request by rhaps0dy**
As discussed :)

edit (msiglreith): Fixes #1319

### CODE REVIEW

**Comment by kvark** [comment]
@homu r+

**Comment by kvark** [comment]
:(

**Comment by kvark** [comment]
Thanks @rhaps0dy !

**Comment by rhaps0dy** [comment]
No problem @kvark. Thank you for the awesome library!

**Pull request merged**
