### PR TITLE
[pre-ll] Fix travis linux build

### PR DESCRIPTION
**Pull request by msiglreith**
Add missing glfw dependencies for the newer trusty images.

Same as #1422

### CODE REVIEW

**Comment by kvark** [comment]
>error: Could not compile `gfx_app`.

hmm

**Comment by msiglreith** [comment]
It actually passed in the travis run on my fork. I hope it was just a sporadic failure.
https://travis-ci.org/msiglreith/gfx/builds/273096073?utm_source=github_status&utm_medium=notification

**Comment by kvark** [comment]
thank you! let's see
bors r+

**Comment by msiglreith** [comment]
Blocked by Travis CI OS X issues, all jobs are stopped. (https://www.traviscistatus.com/)

**Pull request merged**
