### PR TITLE
Format code using rustfmt

### PR DESCRIPTION
**Pull request by krolli**
PR checklist:
- [x] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [x] tested examples with the following backends: dx12, vulkan
- [x] `rustfmt` run on changed code

### CODE REVIEW

**Comment by grovesNL** [comment]
bors r=kvark

**Comment by grovesNL** [comment]
`choco install make` doesn't seem to be working:
> Attempt to get headers for https://sourceforge.net/projects/ezwinports/files/make-4.2.1-without-guile-w32-bin.zip/download failed.
The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://sourceforge.net/projects/ezwinports/files/make-4.2.1-without-guile-w32-bin.zip/download'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."

There is a later version of make (4.3) available there now instead (make-4.3-without-guile-w32.zip)

**Comment by grovesNL** [comment]
Contacted the maintainers of the `make` package on chocolatey to see if we can update the URL. If it takes a while we could temporarily allow CI failures on Windows or manually merge

**Comment by kvark** [comment]
bors try

**Comment by kvark** [comment]
bors retry

**Comment by grovesNL** [comment]
bors r=kvark

**Pull request merged**
