### PR TITLE
Fixed texture size mismatch https://github.com/gfx-rs/gfx/issues/1574

### PR DESCRIPTION
**Pull request by norru**
Details at https://github.com/gfx-rs/gfx/issues/1574

### CODE REVIEW

**Comment by norru** [comment]
This patch can (and should) be backported to branch v0.16 as well.

**Comment by kvark** [comment]
Thanks for tracking this down!
Would you want to rebase  #1572 on `pre-ll` instead of merging this one?

**Comment by norru** [comment]
@kvark @msiglreith: #1572 does include these changes, and does it better. Probably no need to track this further. I would rather take this change when it gets merged back to a release branch - 0.16.x or 0.17 when it's out.

**Comment by kvark** [comment]
Ok, closing then.

**Pull request closed without merging**
