### PR TITLE
Rustfmt crate and enforce formatting with CI

### PR DESCRIPTION
**Pull request by torkleyy**

### CODE REVIEW

**Comment by torkleyy** [comment]
Travis passed. @kvark would you like to review?

**Comment by kvark** [comment]
OMG, that's quite a bit of code...

**Comment by torkleyy** [comment]
@kvark Yeah, but there are no semantic changes.

**Comment by msiglreith** [comment]
I dislike enforcing `rustfmt` as  in the current state the output is sometimes inferior compared to the current code in terms of readability (e.g vertex data definitions in the examples). Hopefully, this will improve in the future!

**Comment by kvark** [comment]
Yes, let's give it more time to mature

**Pull request closed without merging**
