### PR TITLE
[0.3/mtl] update metal-rs and wrap RP switch into an ARP

### PR DESCRIPTION
**Pull request by kvark**
Sibling of #2972 for hal-0.3 with a version bump

### CODE REVIEW

**Comment by kvark** [comment]
bors r=aleksijuvani

**Comment by kvark** [comment]
Added a changelog entry
bors r=aleksijuvani

**Comment by seivan** [comment]
Fixes the minimized/hidden issues mentioned in https://github.com/gfx-rs/gfx/issues/2659 & https://github.com/gfx-rs/wgpu/issues/78

**Comment by kvark** [comment]
Bors retry

**Comment by kvark** [comment]
Bors retry 
One of the bots don't have x11 available?

**Comment by kvark** [comment]
@grovesNL CI is unreliable atm. If you can force merge it, please do.

**Comment by grovesNL** [comment]
Done!

**Pull request merged**
