### PR TITLE
Use locked versions for dependencies. Add fix for libc breaking changes.

### PR DESCRIPTION
**Pull request by mitchmindtree**

### CODE REVIEW

**Comment by mitchmindtree** [comment]
I believe travis is failing as the latest gfx_gl changes haven't been published yet ([issue here](https://github.com/gfx-rs/gfx_gl/issues/24)).

**Comment by kvark** [comment]
@csherratt are you planning to publish `gfx_gl`, or is there something pending still?

**Comment by csherratt** [comment]
I just published it. I didn't last night because I was not sure if we should just wait for updates to libc to 0.2 or not. It looks like things are still broken. I'm looking at it now.

**Comment by kvark** [comment]
@csherratt thanks!

**Comment by csherratt** [comment]
glutin is broken as a result of the libc changes. Otherwise I was able to build this locally.

**Comment by bvssvni** [comment]
[Eco](https://github.com/pistondevelopers/eco) is nice to use for detecting dependency conflicts.

**Comment by csherratt** [comment]
@homu r+

**Pull request merged**
