### PR TITLE
Improve Travis builds

### LINKED ISSUE #998: Speed up Travis builds
https://llogiq.github.io/2016/07/05/travis.html

### PR DESCRIPTION
**Pull request by kvark**
Fixes #998

### CODE REVIEW

**Comment by kvark** [comment]
Looks to be blocked by https://github.com/travis-ci/apt-source-whitelist/issues/45 due to `libsdl2-dev`

**Comment by kvark** [comment]
Hmm, I'm having problems with building `glfw` and `xcb` stuff without `sudo`. I included the corresponding packages but the build scripts still fail. Any help would be appreciated.

**Comment by eugene2k** [comment]
Yeah, I inserted sudo in there because of libsdl. It worked without sudo and on linux you don't have to put glfw or xcb into apt packages. I figure on macOS you don't need them either. Don't know why you put them in there.

**Comment by kvark** [comment]
So glfw and xcb also require sudo? I put them into packages simply because of the errors in their build scripts, hoping that would help.

**Comment by eugene2k** [comment]
I don't think they do. Sorry, I hadn't looked at the errors travis reports and thought there was something wrong with the travis script. I only just looked and realized rust-xcb isn't compiling. What file is its build script looking for that it can't find?

**Comment by kvark** [comment]
I don't know. One way to get more info is to add RUST_BACKTRACE=1 to Travis script. Or even run it through 'strace'. Or maybe do RUST_LOG=debug... Please feel free to experiment if willing to help.

**Comment by eugene2k** [comment]
I'm stuck at glfw for the moment. glfw now requires a higher version of cmake than the one in the kalakris repository. There are other problems with other repositories that are known to contain cmake. So, at the moment, unless there's a whitelisted repository that I missed, we have to use a repository that isn't whitelisted. And that means using sudo. To resolve the original issue(#998), rather than removing sudo, it might be better to switch to to trusty images.

**Comment by kvark** [comment]
Closing in favour of #1091

**Pull request closed without merging**
