### PR TITLE
[mtl] Fix A2BGR10 format mapping

### PR DESCRIPTION
**Pull request by kvark**
Fixes Dota2 after #2116 
PR checklist:
- [ ] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [ ] tested examples with the following backends:
- [ ] `rustfmt` run on changed code

### CODE REVIEW

**Comment by kvark** [comment]
> You don't want to get rid of the RGB10A2Uint format.

It would need to be mapped to `BGR10A2Uint`, which doesn't exist

**Comment by kvark** [comment]
bors delegate=Thomspoon

**Comment by grovesNL** [comment]
bors r=Thomspoon

**Comment by kvark** [comment]
jeez, CI, get your sht together!
bors retry

**Comment by grovesNL** [comment]
AppVeyor's failure is a bit strange:
```
cargo check --all  --exclude gfx-backend-metal --exclude gfx-warden
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading log v0.4.4
error: unable to get packages from source
Caused by:
  [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.)
```
bors retry

**Comment by grovesNL** [comment]
Hmm, why doesn't retry work there?

bors r=Thomspoon

**Comment by kvark** [comment]
Added one extra commit for filtering the copy regions, since apparently some apps want to pass zero dimensions there, and I don't see Vulkan spec forbidding that.
bors r+

**Comment by kvark** [comment]
ALL CI IS BROKEN
bors retry

**Comment by kvark** [comment]
Bors retry

**Comment by kvark** [comment]
Bors r+

**Comment by kvark** [comment]
Bors retry

**Comment by kvark** [comment]
Bors r+

**Comment by kvark** [comment]
Bors r+

**Pull request merged**
