### PR TITLE
[metal] draw_indexed doesn't consume index buffer

### PR DESCRIPTION
**Pull request by omni-viral**
PR checklist:
- [x] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds (might be temporarily impossible, WIP)
   metal backend is broken as well as in master.
- [x] tested examples with the following backends:

---
This change is [Reviewable](https://reviewable.io/reviews/gfx-rs/gfx/1793)

### CODE REVIEW

**Comment by kvark** [comment]
Nice, thank you!
bors r+

**Comment by scoopr** [comment]
For whatever reason my draw_indexed calls now segfault, and I pinpointed that to this commit.
Yet, I can't find anything obviously wrong. The segfault goes away when I add a line like `let buffer = buffer.clone();` before the `msg_send!`, but the indexes are garbled. But then it segfaults if it is just `buffer.clone();`, which I though in this case just returns itself? `println!("{:?}", buffer);` looks legit to me. Help!

**Comment by kvark** [comment]
@scoopr thanks for investigation!
@JohnColanduoni could you take a peek please?

**Comment by omni-viral** [comment]
@scoopr Could you provide the code that gets segfault?

**Comment by omni-viral** [comment]
Now I'm getting segfault after `cargo update`.

**Pull request merged**
