### PR TITLE
Add windows support for travis CI

### PR DESCRIPTION
**Pull request by msiglreith**
Let's see if it works

### CODE REVIEW

**Comment by kvark** [comment]
@msiglreith looks like it worked. Could you remove appveyor then in this PR?

**Comment by grovesNL** [comment]
Not sure if it's a concern, but the last Windows Travis CI build seems to take about twice the length of AppVeyor at the moment (`Ran for 28 min 32 sec`). Maybe there's still room for improvement, or caching will help.

**Comment by kvark** [comment]
bors try

**Comment by kvark** [comment]
Please proceed when ready

**Comment by msiglreith** [comment]
bors r=kvark

**Pull request merged**
