### PR TITLE
Dynamic version detection for EGL

### PR DESCRIPTION
**Pull request by niklaskorz**
Fixes https://github.com/timothee-haudebourg/khronos-egl/issues/11 (is there an according issue in this repo?)
PR checklist:
- [x] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds: fails on my machine (Arch Linux, X11, i3, NVIDIA proprietary driver, RTX 2070 Super), but so does the `master` branch
- [x] tested examples with the following backends: `gfx-backend-gl`

### CODE REVIEW

**Comment by niklaskorz** [comment]
Out of curiosity, why does gfx require EGL >= 1.4? All necessary functions (despite the ones used dynamically from 1.5) seem to exist on 1.2 as well.

**Comment by kvark** [comment]
@niklaskorz thank you for making this test and the PR!
There is no particular reason we require EGL 1.4, the switch to EGL was done very recently, and I haven't done anything with it before, so it all could benefit from improvement :)

**Review by kvark — APPROVED** [review]
Any reason this is a draft?

**Comment by niklaskorz** [comment]
> Any reason this is a draft?

I'm still getting errors of EGL 1.5 symbols not being found in load_minimal, so I guess we'll have to wait for a reply from @timothee-haudebourg before undrafting

**Comment by Gordon-F** [comment]
@niklaskorz If I understand it right, `OpenGL ES 3.0` context creation required [`EGL_KHR_create_context`](https://www.khronos.org/registry/EGL/extensions/KHR/EGL_KHR_create_context.txt) that been introduced only in EGL 1.4.

**Comment by kvark** [comment]
> @niklaskorz If I understand it right, `OpenGL ES 3.0` context creation required [`EGL_KHR_create_context`](https://www.khronos.org/registry/EGL/extensions/KHR/EGL_KHR_create_context.txt) that been introduced only in EGL 1.4.

Is this actually the case? Reading the spec (as well as multiple cases that can be found on the web) tells that:
> `EGL_CONTEXT_MAJOR_VERSION_KHR`
> this token is an alias for `EGL_CONTEXT_CLIENT_VERSION`

So one can specify  `EGL_CONTEXT_CLIENT_VERSION` to `3` (on EGL pre 1.4) for the same outcome, without requiring `EGL_KHR_create_context`.

**Comment by niklaskorz** [comment]
It's finally working on FireTV / Android <10! Now the only thing blocking this PR is https://github.com/timothee-haudebourg/khronos-egl/pull/12


https://user-images.githubusercontent.com/590517/104809623-e3c36b00-57ee-11eb-9f02-34a78d116f6e.mp4

**Review by kvark — APPROVED** [review]
Please rebase and squash

**Comment by niklaskorz** [comment]
> Please rebase and squash

Hm, I might have squashed too much, the PR diff looks weird now.

**Review by kvark — APPROVED** [review]
bors r+

**Pull request merged**
