### PR TITLE
Add init_headless to gfx_window_glutin

### PR DESCRIPTION
**Pull request by torkleyy**
:tada: We are now able to test `gfx` to make it more robust :tada:

### CODE REVIEW

**Comment by torkleyy** [comment]
Huh? Why does it fail on Linux? It works locally, without X... And `glium` is also using `HeadlessContext` on Linux travis.

**Comment by anderejd** [comment]
The error seems to originate from somewhere in here: https://github.com/tomaka/glutin/blob/95434eaf99d78bcc65c22251a791946bdaa84f55/src/api/osmesa/mod.rs#L39

I'm just following this repo for fun and jumping in here during lunch break . Good luck, keep up the good work :)

**Comment by torkleyy** [comment]
@anderejd Yeah, it does. I've created a PR for glutin which introduces better error handling.

> Good luck, keep up the good work :)

Thanks!

**Comment by kvark** [comment]
https://github.com/tomaka/glutin/pull/887

**Comment by kvark** [comment]
@torkleyy is on the roll!
please squash and proceed
@homu delegate=torkleyy

**Comment by torkleyy** [comment]
@homu r+

**Pull request merged**
