### PR TITLE
Replace "colour" with "color".

### PR DESCRIPTION
**Pull request by icefoxen**
Sorry to those who prefer Commonwealth spelling, but it's "color" literally everywhere else in the project.

PR checklist:
- [x] `make` succeeds (on *nix)
- [x] `make reftests` succeeds
- [x] tested examples with the following backends: vulkan, gl
- [x] `rustfmt` run on changed code

### CODE REVIEW

**Comment by icefoxen** [comment]
Rebase what?  I pulled directly from gfx-rs master.  There's no merges to be done.  :confused:

**Comment by kvark** [comment]
> This branch has conflicts that must be resolved

> Conflicting files
examples/colour-uniform/main.rs

**Comment by icefoxen** [comment]
ah heck

**Comment by kvark** [comment]
@icefoxen sorry to bother you again, could you rebase on master?

**Comment by icefoxen** [comment]
closing since rebasing is going to basically require a rewrite at this point and I'm sick of the open PR staring at me.  :/

**Pull request closed without merging**
