### PR TITLE
Remove all old Cargo.toml files as cargo tries to reference removed c…

### PR DESCRIPTION
**Pull request by msiglreith**
…rates

### CODE REVIEW

**Comment by kvark** [comment]
Thank you!
bors r+

**Comment by kvark** [comment]
huh, out timeout is actually 4 hours
TIL
bors r+

**Comment by msiglreith** [comment]
Don't leave us bors! 😭 

bors r=msiglreith

**Comment by kvark** [comment]
last time...
bors r+

**Pull request merged**
