### PR TITLE
Use GL_ARB_program_interface_query to query the shader outputs

### PR DESCRIPTION
**Pull request by csherratt**
OSX will still be broken because it does not support the ARB. It should `work` as it uses the same fallback behaviour as before.

### CODE REVIEW

**Comment by csherratt** [comment]
do not merge yet.

**Comment by kvark** [comment]
awesome, thank you!
@homu r+

**Comment by eugene2k** [comment]
This patch crashes the gfx program if the fragment shader uses gl_FragColor.

**Comment by kvark** [comment]
@eugene2k ugh, sorry! Could you provide the call stack?

**Comment by eugene2k** [comment]
error: XDG_RUNTIME_DIR not set in the environment.
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: DescriptorInit(PixelExport(255, None))', ../src/libcore/result.rs:688
stack backtrace:
   1:     0x55e412fee800 - sys::backtrace::tracing::imp::write::hf7e21f48f7cb711bEju
   2:     0x55e412ff0bf5 - panicking::default_handler::_<closure>::closure.42502
   3:     0x55e412ff069f - panicking::default_handler::hac4d0be12e3129d2Gwy
   4:     0x55e412fe7706 - sys_common::unwind::begin_unwind_inner::hf13a3e016c1e78e1bct
   5:     0x55e412fe7b88 - sys_common::unwind::begin_unwind_fmt::h878e9fd8b85e0857hbt
   6:     0x55e412fede41 - rust_begin_unwind
   7:     0x55e4130226bf - panicking::panic_fmt::h9f005ee999496200zYL
   8:     0x55e412df54f0 - result::Result<T, E>::unwrap::h9589504490288740840
                        at ../src/libcore/macros.rs:29
   9:     0x55e412ddd623 - main::hc40f563c8fa103b9Jpb
                        at src/main.rs:194
  10:     0x55e412ff0324 - sys_common::unwind::try::try_fn::h9896872240422604242
  11:     0x55e412feddd8 - __rust_try
  12:     0x55e412feffb0 - rt::lang_start::h0d9dcd8707a91319Uoy
  13:     0x55e412e09289 - main
  14:     0x7f3ee1b9470f - __libc_start_main
  15:     0x55e412dd21e8 - _start
  16:                0x0 - <unknown>
Process didn't exit successfully: `target/debug/digital-dice` (exit code: 101)

**Comment by eugene2k** [comment]
If you don't specify gl_FragColor as the output variable the above is the callstack. If this is supposed to be the correct behavior, then the error is very confusing.

**Comment by eugene2k** [comment]
This is the call stack for a crash that happens if you set gl_FragColor as the output var:
`error: XDG_RUNTIME_DIR not set in the environment.
thread '<main>' panicked at 'index out of bounds: the len is 4 but the index is 255', <gfx macros>:63
stack backtrace:
   1:     0x5613f0577800 - sys::backtrace::tracing::imp::write::hf7e21f48f7cb711bEju
   2:     0x5613f0579bf5 - panicking::default_handler::_<closure>::closure.42502
   3:     0x5613f057969f - panicking::default_handler::hac4d0be12e3129d2Gwy
   4:     0x5613f0570706 - sys_common::unwind::begin_unwind_inner::hf13a3e016c1e78e1bct
   5:     0x5613f0570b88 - sys_common::unwind::begin_unwind_fmt::h878e9fd8b85e0857hbt
   6:     0x5613f0576e41 - rust_begin_unwind
   7:     0x5613f05ab6bf - panicking::panic_fmt::h9f005ee999496200zYL
   8:     0x5613f05ab832 - panicking::panic_bounds_check::h164576bc413dcf81FXL
   9:     0x5613f0381f3e - gui_pipe::Init<'a>...gfx..pso..PipelineInit::link_to::h0d15101437e4b4bcdka
                        at /home/me/projects/DigitalDice/<gfx macros>:63
  10:     0x5613f037f71d - factory::FactoryExt::create_pipeline_from_program::h9000462661794021734
                        at gfx/src/render/src/factory.rs:115
  11:     0x5613f037f4d6 - factory::FactoryExt::create_pipeline_state::h10239421458233912648
                        at gfx/src/render/src/factory.rs:104
  12:     0x5613f037e8fc - factory::FactoryExt::create_pipeline_simple::h7454582643033952028
                        at gfx/src/render/src/factory.rs:133
  13:     0x5613f036660e - main::hd2c6b54b380c675bJpb
                        at src/main.rs:194
  14:     0x5613f0579324 - sys_common::unwind::try::try_fn::h9896872240422604242
  15:     0x5613f0576dd8 - __rust_try
  16:     0x5613f0578fb0 - rt::lang_start::h0d9dcd8707a91319Uoy
  17:     0x5613f0392289 - main
  18:     0x7f476298d70f - __libc_start_main
  19:     0x5613f035b1e8 - _start
  20:                0x0 - <unknown>
Process didn't exit successfully: `target/debug/digital-dice` (exit code: 101)
`

**Comment by kvark** [comment]
Hmm, I don't see the new queries skipping over `gl_` stuff, so they should catch `gl_FragColor`.
@csherratt any ideas?

**Comment by eugene2k** [comment]
It doesn't seem to me that there's any part of the code that actually tries to check for gl_FragColor or FragData when checking for output vars.

**Comment by kvark** [comment]
You might be hitting this rare case when the queries are supported but you are using compatibility shaders. I wonder how this was supposed to work in general... There have to be some interaction rules defined in the extension itself.

**Comment by eugene2k** [comment]
Doesn't look that rare to me... Same crash on both the intel card and the geforce card.

**Comment by kvark** [comment]
@eugene2k I'd expect most of the cards that support 3.0 to also support 3.2 core, for which `gl_FragColor` is deprecated.

**Comment by eugene2k** [comment]
Is this extension supposed to only work with the core profile? The spec says it's written against opengl 4.2 compatibility profile.

I was working with 120 shader and gfx quite obviously uses 120 shaders in its examples.

**Comment by kvark** [comment]
@eugene2k might as well be our bug, I don't know exactly how the extension is supposed to handle this. Let's hear @csherratt , maybe he understands better.

**Comment by fkaa** [comment]
From the [wiki](https://www.opengl.org/wiki/GLAPI/glGetProgramResource):
> For the property `GL_LOCATION`, a single integer identifying the assigned location for an active uniform, input, output, or subroutine uniform variable is written to params​. For input, output, or uniform variables with locations specified by a layout qualifier, the specified location is used. For vertex shader input or fragment shader output variables without a layout qualifier, the location assigned when a program is linked is written to params​. For all other input and output variables, the value -1 is written to params​. For uniforms in uniform blocks, the value -1 is written to params​.

> For the property `GL_LOCATION_INDEX`, a single integer identifying the fragment color index of an active fragment shader output variable is written to params​. If the active variable is an output for a non-fragment shader, the value -1 will be written to params​.

@csherratt isn't it the latter case we want? (not `GL_LOCATION`)

**Pull request merged**
