### PR TITLE
[v0.17] Update glutin, winit

### PR DESCRIPTION
**Pull request by alexheretic**
Cherry pick 734a4fdcb710c89aca52a1a774de18403ef8011f to release support for glutin 0.13 / winit 0.11
PR checklist:
- [x] tested examples with the following backends: gl

### CODE REVIEW

**Comment by kvark** [comment]
@alexheretic which of those do you need published? all of them?

**Comment by alexheretic** [comment]
Just gfx_window_glutin will do


On 2 Mar 2018 19:25, "Dzmitry Malyshau" <notifications@github.com> wrote:

@alexheretic <https://github.com/alexheretic> which of those do you need
published? all of them?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/gfx-rs/gfx/pull/1866#issuecomment-370026378>, or mute
the thread

**Comment by kvark** [comment]
https://crates.io/crates/gfx_window_glutin/0.21.0

**Comment by alexheretic** [comment]
@kvark Thank you!

**Pull request merged**
