### PR TITLE
Remove render parts

### PR DESCRIPTION
**Pull request by msiglreith**
As dicussed remove the `render` portions as we already have a `gfx-render` repository in the organization, the current code is more or less unmaintained and focus on the low level API only for the `gfx`, separating it from higher level wrappers.

PR checklist:
- [ ] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [ ] tested examples with the following backends:

### CODE REVIEW

**Comment by kvark** [comment]
Looks green.
bors r+

**Comment by grovesNL** [comment]
CI failure is unrelated:
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

**Comment by kvark** [comment]
bors retry

**Comment by JohnDoneth** [comment]
CI Failure again seems unrelated...?
```apt-get install failed
Packages
  404  Not Found
Err:80 http://ppa.launchpad.net/george-edison55/precise-backports/ubuntu trusty/main i386 Packages
  404  Not Found
Ign:81 http://ppa.launchpad.net/george-edison55/precise-backports/ubuntu trusty/main all Packages
Fetched 7,623 kB in 22s (344 kB/s)
Reading package lists...
W: The repository 'http://apt.llvm.org/precise llvm-toolchain-precise-3.8 Release' is not signed.
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
W: The repository 'http://ppa.launchpad.net/george-edison55/precise-backports/ubuntu trusty Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/george-edison55/precise-backports/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/george-edison55/precise-backports/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install xdotool cmake cmake-data libxxf86vm-dev libxinerama-dev libxinerama1 libxcursor-dev libxcursor1 libglfw-dev libosmesa6-dev libxi-dev libxrandr-dev g++-5 gcc" failed and exited with 100 during .
```

**Comment by kvark** [comment]
bors retry

**Comment by msiglreith** [comment]
bors r=kvark

**Pull request merged**
