### PR TITLE
[v0.17] Update winit -> 0.15, glutin -> 0.16

### PR DESCRIPTION
**Pull request by alexheretic**
Bump affected `gfx_window_glutin`, `gfx_window_dxgi`  versions for release

PR checklist:
- [x] tested examples with the following backends: gl

### CODE REVIEW

**Comment by francesca64** [comment]
Is there a reason cocoa 0.9 is being used? winit and metal-rs both pull in 0.15.

**Comment by alexheretic** [comment]
I don't think the pre-ll gfx_window_metal is maintained _(or ever used?)_. I just update the winit reference there so there is one winit version used throughout the projects, but I guess I can probably stop updating the release version.

**Comment by alexheretic** [comment]
@kvark I'd appreciate a _gfx_window_glutin_ release when you get time

**Comment by kvark** [comment]
https://crates.io/crates/gfx_window_glutin/0.24.0
https://crates.io/crates/gfx_window_dxgi/0.15.0

**Pull request merged**
