### PR TITLE
[ll] Initial work for command buffer rework [37/..]

### PR DESCRIPTION
**Pull request by msiglreith**
Following the approach presented by #1416 

* Rework `Buffer` trait to match the new `RawCommandBuffer` interface for primary command buffers
* Implement strong-typed shims for command buffer types.
* Add  `RenderPassInlineEncoder` as additional shim for renderpass handling
* Start implementation of vulkan/dx12/(gl) command buffer reworks based on the `corell` backends
* Merge `Resources` into `Backend` as it's easier to work with..
* Add a few new resource types (renderpass, framebuffer, descriptorset, ...) and corresponding device creation methods but mostly to get the command buffer interface correct atm.

Current implementation issues:
* dx12: Renderpasses need to be emulated, requiring to cache the current renderpass information in the command buffer. In the future we could optimize memory storage by storing these per command pool as we would only need one cache/pool instead of one cache/command buffer.

* dx12: Indirect calls are more advanced compared to vulkan, therefore we need to create a few `CommandSignatures` upfront on initialization and share them with each command buffer, but shouldn't be a blocker.

cc #1102 

Edit: separate branch similar to the old `ll` branch. It doesn't build yet, but to keep you updated from time to time..

### CODE REVIEW

**Comment by kvark** [comment]
The merging of `Resources` and `Backend` seems to do well.
All good stuff!

**Comment by kvark** [comment]
> Edit: separate branch similar to the old ll branch. It doesn't build yet, but to keep you updated from time to time..

Hmm, this PR is targeted at `master` though. Is this a mistake?

**Comment by msiglreith** [comment]
> Hmm, this PR is targeted at master though. Is this a mistake?

Oh, I need to create an empty branch first and push it..

**Comment by msiglreith** [comment]
Updated the `ll` branch to be even with `master` and retargeted the branch to `ll`.

**Pull request merged**
