### PR TITLE
Fix doc formatting and add a bit of detail

### PR DESCRIPTION
**Pull request by AnthIste**

### CODE REVIEW

**Comment by kvark** [comment]
Oh snap! How come our build is red now?

**Comment by AnthIste** [comment]
```
running 2 tests
test init_0 ... ok
test init_existing_0 ... FAILED
failures:
---- init_existing_0 stdout ----
	error[E0463]: can't find crate for `piston`
 --> <anon>:2:5
  |
2 |     extern crate piston;
  |     ^^^^^^^^^^^^^^^^^^^^
```

it seems it's trying to execute stuff from the doc comments. I put in the `\`\`\`no_run` bit just like the other doc comment?

**Comment by AnthIste** [comment]
```
running 2 tests
test init_0 ... ok
test init_existing_0 ... FAILED
failures:
---- init_existing_0 stdout ----
	error[E0463]: can't find crate for `piston`
 --> <anon>:2:5
  |
2 |     extern crate piston;
  |     ^^^^^^^^^^^^^^^^^^^^
```

It's trying to execute the doc comments o.O. I added a `no_exec` bit to the code snippet?

**Comment by kvark** [comment]
Thanks!
@homu r+

**Pull request merged**
