### PR TITLE
Expose Vulkan device_type from hal

### PR DESCRIPTION
**Pull request by jackmott**
Notes:

I ran rustfmt on files I touched, this caused many changes in some, hence the wild diffs.
make reftests failed, I believe unrelated, see the note below in the PR checklist
I have no way to build the metal backend, so I have not built it. Relying on bors for now.

### Backends

* Vulkan - This gets exposed exactly as it does by Vulkan/ash
* Metal - Metal docs say that is_low_power() is true for integrated, false for discrete. So these are the only two values Metal will return, using this to decide.
* DX11/12 - I return VirtualGpu if software rendering is true, otherwise discrete. I did not find that any more detailed info is exposed, but I am uncertain.
* OpenGL - I always return discrete, it does not appears OpenGL can expose this information.

PR checklist:
- [x] `make` succeeds (on *nix)
- [x] `make reftests` succeeds  (it did not, filed issue #2358 )
- [x] tested examples with the following backends:Vulkan
- [x] `rustfmt` run on changed code

### CODE REVIEW

**Comment by jackmott** [comment]
I can, I suppose best way is start a fresh PR?
Alternatively I could tag the lines actually changed in a comment, there aren't many. Would that work?

**Comment by kvark** [comment]
@jackmott `git rebase -i master` and then squash and edit some

**Comment by jackmott** [comment]
ok I gave it a try but appear to have made of mess of things with git. I'm going to do a new PR.

**Comment by kvark** [comment]
You know you can just force-push to this branch and avoid creation of new PRs?
Also, something is wrong with the "Exposing Vulkan's ..." commit, it's always put the last in Github history. Maybe the date is wrong?

**Comment by jackmott** [comment]
oh yeah, time was wrong on my windows boot. it does then when i switch.  new pr is already up.

**Pull request closed without merging**
