### PR TITLE
Added 'static lifetime to Resources

### PR DESCRIPTION
**Pull request by csherratt**

### CODE REVIEW

**Comment by csherratt** [comment]
@homu r+

**Comment by kvark** [comment]
I recall doing this at some point and then falling back because this is too limiting. @csherratt are you sure about the change? Where did you need it?

**Comment by bvssvni** [comment]
Found it https://github.com/gfx-rs/gfx/pull/708.

**Comment by bvssvni** [comment]
Non-static lifetimes in such types should be rare. `Resources` should always be `'static`, I guess, so lifetimes on the associated type does not seem to make sense.

If there is a problem with it then we could fix it in a later version of Gfx.

**Comment by kvark** [comment]
It's a one way road though. Changing it back may break some code.
I'd like to see why exactly it is needed now. Perhaps, we could find a better way?

**Comment by csherratt** [comment]
Actually your change shows another possible solution to my problem. I was hacking on `gfx_scene` and could not figure out a nice way of telling the compiler that the lifetime of the resources was at least as long as the lifetime as the reference. Your change shows a (verbose) way of doing so.

I don't have a problem with this being rolled back.

**Comment by bvssvni** [comment]
I'm OK with this being rolled back too, I don't think it breaks much code if we do it now.

**Pull request merged**
