### PR TITLE
[0.6/dx11] Bugfixes

### PR DESCRIPTION
**Pull request by cwfitzgerald**
Fixes compilation issues in release, errant warnings, and creation of DeferredContext1.

Waiting for @m4b to confirm if the context fix works.

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
Going ahead with this PR despite it not fixing the rendering bug as it doesn't make it worse.

**Review by kvark — APPROVED** [review]
bors r+

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
bors retry

**Pull request merged**
