### PR TITLE
Unbloat the build

### PR DESCRIPTION
**Pull request by kvark**
Removes dependency on failure and refactors our errors a bit.
This change reduces the gfx-hal build time from 45 sec to just 8 sec on my machine :tada: 

PR checklist:
- [x] `make` succeeds (on *nix)
- [x] `make reftests` succeeds
- [x] tested examples with the following backends: linux
- [ ] `rustfmt` run on changed code

### CODE REVIEW

**Comment by kvark** [comment]
bors r=grovesNL

**Comment by kvark** [comment]
bors r=grovesNL

**Comment by kvark** [comment]
bors r=grovesNL

**Comment by matklad** [comment]
do you know which part of the speed up is attributed to the removal of failure, and which to the other refactorings? I wonder if “removing failure may make your build five times faster” is an accurate thing to say :)

**Comment by kvark** [comment]
Iirc, it was failure precisely that was making us slow.

**Pull request merged**
