### PR TITLE
[mtl] build internal shaders with debug info

### PR DESCRIPTION
**Pull request by kvark**
Helps investigating #2364
PR checklist:
- [ ] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [ ] tested examples with the following backends:
- [ ] `rustfmt` run on changed code

### CODE REVIEW

**Comment by grovesNL** [comment]
This doesn't seem to work on Travis:
```
--- stderr
metal: error: unknown argument: '-MO'
thread 'main' panicked at 'shader compilation failed', src/backend/metal/build.rs:72:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
But we rely on Travis for building portability... so not sure how to proceed.

**Comment by Michael-Lfx** [comment]
Is the PR abandoned? cc @kvark

**Comment by kvark** [comment]
Please feel free to complete it.

**Comment by kvark** [comment]
@Michael-Lfx the only thing missing here is adding a check at run-time for XCode 10 before adding those debug flags. Similar but different flags exist on XCode 9 as well, so using those appropriately would be good too.

**Comment by kvark** [comment]
I really procrastinate when it comes to build systems, sorry. Don't know what I'd be doing without @grovesNL help, but this PR is still kept in the air.

**Comment by kvark** [comment]
@grovesNL any idea on how to finish this? :)
just trying to clean up our open PRs

**Comment by GabrielMajeri** [comment]
@kvark According to [this page](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode), GH Actions already has Xcode 11 by default, so we can drop the `.travis.yml` changes.

As for the build flags, I'm guessing they can stay the same?

**Comment by kvark** [comment]
Right, that sounds reasonable. Note that travis YML is no more.
These changes now need to go through our github action scripts.

**Pull request closed without merging**
