### PR TITLE
 Refactor ChannelType values to have consistant prefixes 

### LINKED ISSUE #2458: Refactor value name of ChannelType for consistency
```rust
pub enum ChannelType {
    /// Unsigned normalized.
    Unorm,
    /// Signed normalized.
    Inorm,
    /// Unsigned integer.
    Uint,
    /// Signed integer.
    Int,
    /// Unsigned floating-point.
    Ufloat,
    /// Signed floating-point.
    Float,
    /// Unsigned scaled integer.
    Uscaled,
    /// Signed scaled integer.
    Iscaled,
    /// Unsigned normalized, SRGB non-linear encoded.
    Srgb,
}
```

Should they remove prefix *I* for those **Signed** value because `Float` and `Int` are not consistent with `Unorm` and `Inorm`? For example just let `Inorm` be `Norm`.

https://github.com/gfx-rs/gfx/blob/bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7/src/hal/src/format.rs#L195

### PR DESCRIPTION
**Pull request by hgallagher1993**
Fixes #2458 
PR checklist:
- [X] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [X] tested examples with the following backends: gl
- [ ] `rustfmt` run on changed code

`make reftests` failed but I'm not sure why it just returned `thread 'main' panicked at 'failed to open/parse the scene: Parser(ExpectedIdentifier, Position { col: 27, line: 75 })', src/libcore/result.rs:1009:5` I could manually run `cargo run --features vulkan / gl` though

### CODE REVIEW

**Comment by hgallagher1993** [comment]
Cool, I'll make those changes either this evening or tomorrow :+1:

**Comment by hgallagher1993** [comment]
@kvark I renamed `Usrgb` back to `Srgb` and got `make reftests` to run as well so I think that should be it now

**Comment by hgallagher1993** [comment]
I'll fix the build failures now

**Comment by hgallagher1993** [comment]
Right hopefully no more errors pop up :smile:

**Comment by kvark** [comment]
Could you squash the last 4 commits into one (or everything into one), please?

**Comment by hgallagher1993** [comment]
That should be it I think :+1:

**Comment by kvark** [comment]
Thanks!
Bors r+

**Comment by hgallagher1993** [comment]
No problem :smile:

**Pull request merged**
