### PR TITLE
Fixed the PSO macro to use scissor properly

### PR DESCRIPTION
**Pull request by kvark**
Probably fixes https://github.com/PistonDevelopers/conrod/pull/710

TODO: port to master branch

### CODE REVIEW

**Comment by bvssvni** [comment]
Nice!

**Comment by kvark** [comment]
@bvssvni please publish gfx-0.10.2 if you can, from this branch. The version is already bumped.

**Comment by bvssvni** [comment]
@kvark Seems it was bumped to 0.10.1 instead of 0.10.2. There is a 0.10.1 version on crates.io.

**Comment by bvssvni** [comment]
0.10.1 was published in this PR https://github.com/gfx-rs/gfx/pull/912

**Comment by kvark** [comment]
@bvssvni yeah, I didn't realize 0.10.1 is already published, so I bumped the version again right after this PR.

**Comment by bvssvni** [comment]
@kvark Unfortunately the v0.10 branch does not contain the fix https://github.com/gfx-rs/gfx/pull/912/files#diff-e76accb5ddad96024c8ebca0ad05ee68R116, so the code will break downstream.

**Comment by kvark** [comment]
wait, aren't you using 0.10 version from crates.io?

**Pull request merged**
