### PR TITLE
More Emscripten support

### PR DESCRIPTION
**Pull request by kvark**
## Intro
This is a big follow-up to #1681 and #1685

After being blocked by https://github.com/rust-lang/rust/issues/47023, I got stuff building in release, so continued porting the examples over. Note: there is a lot of shader code duplication, we need some (simple) templating/preprocessor there.

## Environment

OS: Linux + Firefox Nightly,

Emscripten: built from source with the following changes:
  - integrated https://github.com/kripken/emscripten/pull/5951
  - `USE_WEBGL2=1` is forcefully set in "settings.js"

## Status

🎉 Work 🎉 : triangle, cube, flowmap, blend, gamma, terrain, ubo_tilemap

Almost works: mipmap - see #1704

Not tested: deferred (too many shaders!), performance

Blocked by the lack of buffer mapping: instancing

Blocked by the lack of geometry/tessellation shader support: particle, render_target, terrain_tessellated

Fail to run: shadow, skybox - see #1705

## Proof
gfx-emscripten-ubo_tilemap

### CODE REVIEW

**Comment by grovesNL** [comment]
Looks great! Have you tried `FULL_ES3=1` to emulate `glMapBuffer`? Just wondering whether the emulation is sufficient for now.

**Comment by torkleyy** [comment]
Looks good to me so far, but didn't check the tilemap shader.

---

Reviewed 46 of 48 files at r1.
Review status: 34 of 36 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[examples/shadow/shader/forward_300_es.glslf, line 35 at r1](https://reviewable.io:443/reviews/gfx-rs/gfx/1706#-L1XDw3oLxH0OdW8PR_n:-L1XDw3oLxH0OdW8PR_o:bfwyuvu) ([raw file](https://github.com/gfx-rs/gfx/blob/10861b2976117bd63d47f6e39f1b06ea1a9b98c3/examples/shadow/shader/forward_300_es.glslf#L35)):*
> ```
> void main() {
> 	vec3 normal = normalize(v_Normal);
> 	vec3 ambient = vec3(0.05, 0.05, 0.05);
> ```

You could make that a constant or uniform variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gfx-rs/gfx/1706#-:-L1XDbPG5Smv2pILydmC:bpsuscn)*

**Comment by kvark** [comment]
Thanks @torkleyy and @grovesNL !

> Have you tried FULL_ES3=1 to emulate glMapBuffer

I haven't yet tried full ES3, no. Sounds interesting to do.

> You could make that a constant or uniform variable.

True, although, I was only copying the shaders (hence the mentioned need for a preprocessor). There is no new code.

**Comment by kvark** [comment]
I suspect the worst - upstream breakage of glutin, given that the PR doesn't touch cargo manifests :(

**Comment by kvark** [comment]
nvm, I forgot that we were (temporarily!) using glutin as a git dependency :)

**Comment by kvark** [comment]
bors r=msiglreith

**Pull request merged**
