### PR TITLE
Add GCC to path.

### LINKED ISSUE #932: Fix win32 GNU toolchain build for AppVeyor
Something is pulling miniz-sys, which can't be found:

>running: "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-o" "C:\\projects\\gfx\\target\\debug\\build\\miniz-sys-d03126dbc9ee0074\\out\\miniz.o" "-c" "miniz.c"
 
>failed to execute command: The system cannot find the file specified. (os error 2)
Is `gcc.exe` not installed? (see https://github.com/alexcrichton/gcc-rs#compile-time-requirements for help)

### PR DESCRIPTION
**Pull request by vickenty**
Fixes #932 (maybe)

### CODE REVIEW

**Comment by kvark** [comment]
Looks like there is more to it:
> miniz.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
 /* miniz.c v1.16 beta r1 - public domain deflate/inflate, zlib-subset, ZIP reading/writing/appending, PNG writing

**Comment by kvark** [comment]
@bvssvni are you aware of anyone building piston-image crate for windows with GNU toolchain?

**Comment by vickenty** [comment]
I tried disabling flate2 dependency  (https://github.com/vickenty/gfx/commit/c47503ab5a051bcbafd9b9a47b2e958c8361fbb4), but then blend, flowmap, skybox and ubo_tilemap examples fail to run without it.

**Comment by kvark** [comment]
Time for the stable MSVC build went up from 19 min to 24 min.

**Comment by kvark** [comment]
Hooray!
@homu r+

**Pull request merged**
