### PR TITLE
[dx/master] Rollup of DX Fixes

### PR DESCRIPTION
**Pull request by cwfitzgerald**
Got a little behind here; rolls up #3444 #3446 #3448 #3452 #3456 #3458 and #3465. 

#3449 seems to have been obsoleted by a previous change in master: https://github.com/gfx-rs/gfx/blame/fa323527758d35a3913815e62bcb0e08511f7384/src/backend/dx12/src/device.rs#L2443-L2449. Could you just validate that this change does indeed serve the same purpose?

### CODE REVIEW

**Comment by kvark** [comment]
thats... an impressive list!
bors r+

**Comment by kvark** [comment]
> Could you just validate that this change does indeed serve the same purpose?

the blame points to lines from 2017, so looks like the link is wrong

**Review by kvark — APPROVED** [review]

**Comment by kvark** [comment]
bors retry

**Comment by cwfitzgerald** [comment]
> 
> 
> > Could you just validate that this change does indeed serve the same purpose?
> 
> the blame points to lines from 2017, so looks like the link is wrong

It was the line in the middle from two months ago: more precise blame: https://github.com/gfx-rs/gfx/blame/fa323527758d35a3913815e62bcb0e08511f7384/src/backend/dx12/src/device.rs#L2445

**Comment by kvark** [comment]
My change didn't check the target format features, so yours seems to still be needed.

**Comment by cwfitzgerald** [comment]
Alright, I'll follow up with a proper merge of that, need to actually think about it.

**Pull request merged**
