### PR TITLE
Mipmap generation for GL, merged

### PR DESCRIPTION
**Pull request by snuk182**

### CODE REVIEW

**Comment by kvark** [comment]
@retep998 ugh, d3d12 broke: https://ci.appveyor.com/project/kvark/gfx/build/1.0.1373/job/tbitevgwm0ai1fop#L823

Sounds like a breaking change due to safety?

**Comment by msiglreith** [comment]
That was mine break https://github.com/msiglreith/comptr-rs/pull/2
Other branches have been updated to wio already..

**Comment by kvark** [comment]
Travis also fails: https://travis-ci.org/gfx-rs/gfx/jobs/272093343#L1048
> error: failed to run custom build command for `glfw-sys v3.2.2`
process didn't exit successfully: `/home/travis/build/gfx-rs/gfx/target/debug/build/glfw-sys-fe35f86283832be6/build-script-build` (exit code: 101)

Seems unrelated, but still sad :(

**Comment by msiglreith** [comment]
Another missing patch for this branch, meh..
https://github.com/gfx-rs/gfx/pull/1422/files / https://github.com/gfx-rs/gfx/pull/1423/files

I can apply them later on, currently no time.

**Comment by kvark** [comment]
ok, @msiglreith, thanks for the info!
Don't want to torture @snuk182 any more, let's ship it and follow up with GL/appveyor fixes.

**Pull request merged**
