### PR TITLE
Improve instanced functions documentation

### PR DESCRIPTION
**Pull request by Bastacyclop**
I was a bit confused by those "counts"

### CODE REVIEW

**Comment by kvark** [comment]
Please add the license headers following other examples.

**Comment by kvark** [comment]
Note that GLSL 120 shaders here are useless until we support the EXT version of instancing GL extensions. It's just FYI - no need to remove them, I suppose, we should instead just get the proper EXT instancing support.

**Comment by kvark** [comment]
@homu r+

**Comment by kvark** [comment]
@Bastacyclop well done, thanks for the PR!

**Comment by Bastacyclop** [comment]
Glad I could help.

**Pull request merged**
