### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by fkaa**
Fixme! :shipit:

### CODE REVIEW

**Comment by cmr** [comment]
@humo: r+

**Comment by bvssvni** [comment]
@fkaa You are awesome!

**Comment by cmr** [comment]
@homu: r+

**Comment by LaylConway** [comment]
The hidden arrow on the logo is a nice touch!

**Comment by cmr** [comment]
Hm, something is wrong with our travis config. Doc generation is broken.

**Comment by kvark** [comment]
@cmr yes, it would be great to have you taking a look at it.

**Comment by kvark** [comment]
@homu retry

**Pull request merged**
