### PR TITLE
[WIP] Use cargo workspace. Move gfx_app in its own crate

### PR DESCRIPTION
**Pull request by ama0**
This is a first prototype on using cargo workspace for the whole project. (#1248)
gfx_app is no longer the 'main crate'. It is moved into src/gfx_app

I left the old dependencies in the main `Cargo.toml` to make it easier to compare and see what may be a cause of error.

What is working:
- cargo build
- cargo run --example [all examples work]
- cargo test

What is not working:
- cargo build --all
- cargo test --all
Both throw a bunch of errors because the platform is wrong. See [Provide a way to run cargo subcommands on all crates in the workspace #2878](https://github.com/rust-lang/cargo/issues/2878#issuecomment-292986795) This seems to be the blocker right now.

### CODE REVIEW

**Comment by torkleyy** [comment]
@ama0 Since I presumably created lots of conflicts with my formatting PR, may I try to do this workspace-PR? Or would you prefer to do it yourself?

**Comment by ama0** [comment]
@torkleyy Sure, go on 👍 Just remember that there's still this blocking issue

**Comment by torkleyy** [comment]
@ama0 Maybe we could just do a `-p` on each while the issue remains unsolved?

**Comment by ama0** [comment]
@torkleyy I don't know what `-p` means in this context :(

**Comment by torkleyy** [comment]
@ama0 From `cargo  build --help`:

```
    -p SPEC, --package SPEC ...  Package to build
```

**Comment by ama0** [comment]
@torkleyy I'm not sure how this would solve the `build --all` issue. I would just update this PR to the newest dependency changes in gfx, gfx_app and all examples to keep the changes to master as small as possible and wait for a fix in cargo.

**Comment by torkleyy** [comment]
Well, I'm just working on the cargo issue, but you have to be patient - not a cargo expert :smile:

**Comment by torkleyy** [comment]
My PR is in this week's TWIR. IIRC the next release should be in 2 weeks.

**Comment by ama0** [comment]
@torkleyy Congratulations 👍 

I've updated this PR so it stays closer to current master. Currently it looks like this:
* main crate is `gfx` with its code in `src/render/src/lib.rs` (There's no `Cargo.toml` in `src/render/..` anymore, so dependencies have to point to to the root crate
* gfx_app is now in `src/gfx_app`

There are still some issues I'm not sure how to solve since I'm not that deep into gfx internals.
* `window/glfw/Cargo.toml` and `window/sdl/Cargo.toml` have a dependency on the renderer. This leads to a cyclic dependency since both are also dependencies of gfx. I commented both entries to make it build.

**Comment by msiglreith** [comment]
> window/glfw/Cargo.toml and window/sdl/Cargo.toml have a dependency on the renderer. This leads to a cyclic dependency since both are also dependencies of gfx. I commented both entries to make it build.

They shouldn't depend on `render`, this should be fixed if possible.

**Comment by ama0** [comment]
I removed the changes to `.gitignore` and squashed the little change in `contrib.md` into the main commit. (see: https://github.com/gfx-rs/gfx/issues/1248#issuecomment-307075120)

**Comment by torkleyy** [comment]
Okay, the flag landed on stable.

**Comment by kvark** [comment]
@ama0 would you be able to rebase this?

**Comment by ama0** [comment]
Thanks for the heads up. I'll try to look into it in a few days.

**Comment by ama0** [comment]
Thanks for the heads up. I'll try to look into it in a few days.

**Comment by torkleyy** [comment]
Guess this can be closed now that another PR implemented it.

**Comment by bjadamson** [comment]
https://github.com/gfx-rs/gfx/pull/1417

**Comment by kvark** [comment]
Thanks everyone, this is done!

**Pull request closed without merging**
