### PR TITLE
Gamma example WebGL support

### PR DESCRIPTION
**Pull request by kvark**

### CODE REVIEW

**Comment by kvark** [comment]
Weirdly, even the triangle example is failing link now. May be an obscure Rustc bug... will file shortly.

**Comment by kvark** [comment]
> error: failed to write dep-graph to `/home/travis/build/gfx-rs/gfx/target/debug/incremental/mipmap-ji74ebttqtcy/s-ews5lr3r3g-hrukv6-working/dep-graph.bin`: No space left on device (os error 28)

ugh...
bors r=msiglreith

**Comment by msiglreith** [comment]
We probably should disable incremental compilation for nightly builds..

**Comment by kvark** [comment]
Yes, exactly. Unless Travis allows us to get more space.

**Comment by kvark** [comment]
bors r=msiglreith

**Comment by kvark** [comment]
And now I wonder if bors is doing anything...

**Comment by msiglreith** [comment]
probably needs a rebase

**Comment by kvark** [comment]
bors r=msiglreith

**Pull request merged**
