### PR TITLE
Update cargo.toml so that docs.rs works

### PR DESCRIPTION
**Pull request by Lokathor**
This adds a line so that docs.rs builds the dx12 backend using the window target.

This way we get docs.

### CODE REVIEW

**Comment by Lokathor** [comment]
Closes https://github.com/gfx-rs/gfx/issues/2536

**Comment by Lokathor** [comment]
I dunno what bors is waiting on here, but this PR is complete and whoever reviews it can feel free to merge it the second they approve it.

**Comment by kvark** [comment]
Awesome thank you!
Could you squash this please?

**Comment by Lokathor** [comment]
I really don't know how do to that, but I'll look into doing something about it after work.

**Comment by kvark** [comment]
@Lokathor way I do it is: "git rebase -i master" (assuming you branched off `master`) and then mark everything but the first commit for squashing

**Comment by Lokathor** [comment]
I just did all these edits in the browser because it's only toml files. I didn't even clone the repo.

I can try to either squash it or redo it as a single commit after work.

**Comment by kvark** [comment]
@Lokathor ok, if it's non-trivial to you, I'll just wait for CI status and merge with squashing manually.
We ask users to squash because the main workflow is Bors, and it doesn't know how to squash.

**Comment by Lokathor** [comment]
Alright, I tried to squash it down as best I could.

**Comment by kvark** [comment]
@Lokathor I'm afraid this is not the result we expect. There is still 6 commits, plus the last one is a merge commit.
Don't want to hold you on this any more, let's proceed manually.
You are welcome to experiment with more rebases in future PRs ;)

**Comment by Lokathor** [comment]
haha, yeah okay. Unfortunately, I'm very bad at git history stuff. It's perhaps my worst skill.

**Pull request merged**
