### PR TITLE
Fixed support for OpenGL drivers without VAO

### PR DESCRIPTION
**Pull request by ozkriff**
backport of https://github.com/gfx-rs/gfx/pull/1323 on v0.16 branch

See https://github.com/gfx-rs/gfx/issues/1415

### CODE REVIEW

**Comment by ozkriff** [comment]
Ouch. It seems like metal backend needs to be updated too.

**Comment by ozkriff** [comment]
It turns out it's not that easy to backport metal-rs 3.0 -> 4.0 upgrade as I know nothing about both LL-related and metal-related code. Can someone help me to make this work? :-(

**Comment by kvark** [comment]
Thanks!
bors r+

**Comment by kvark** [comment]
Looks like some dependency still needs to be bumped:
https://travis-ci.org/gfx-rs/gfx/jobs/262206292#L1639

**Comment by ozkriff** [comment]
:( I'll try to fix that tomorrow

**Comment by msiglreith** [comment]
@ozkriff Could include #1423 into this PR, which should fix the remaining build issues? The other PR requires the metal upgrade resulting in conflicts with this one, but that's not worth it imo.

**Comment by kvark** [comment]
let's try again now
bors r+

**Comment by ozkriff** [comment]
oh, wow. thanks, bors!

**Pull request merged**
