### PR TITLE
[WIP] [ll] Update metal backend to ll [35/..]

### PR DESCRIPTION
**Pull request by msiglreith**
I tried to update the current `metal` backent and `window_metal` to the latest `core` changes.
The current changes are very rough and I'm unable to test them (only checked that it compiles) due to lack of hardware.

_If someone would be able to check the examples if they run (and fix possible bugs) I would be very glad!_

examples.
(Most of the changes adopted from the `metalll` backend)
cc #1321 

Edit: Currently doesn't create depth stencil textures for the swapchain, which mostly like will crash some

### CODE REVIEW

**Comment by kvark** [comment]
```
       Compiling gfx_device_metal v0.3.0 (file:///Users/kvark/Code/gfx/src/backend/metal)
    error[E0308]: mismatched types
      --> src/backend/metal/src/factory.rs:88:72
       |
    88 |                 .new_buffer_with_data(unsafe { mem::transmute(data) }, info.size as u32, usage)
       |                                                                        ^^^^^^^^^^^^^^^^ expected u64, found u32
     
    error[E0308]: mismatched types
       --> src/backend/metal/src/factory.rs:550:36
        |
    550 |                             width: w as u32,
        |                                    ^^^^^^^^ expected u64, found u32
     
    error[E0308]: mismatched types
       --> src/backend/metal/src/factory.rs:560:36
        |
    560 |                             width: w as u32,
        |                                    ^^^^^^^^ expected u64, found u32
     
    error[E0308]: mismatched types
       --> src/backend/metal/src/factory.rs:562:36
        |
    562 |                             depth: d as u32,
        |                                    ^^^^^^^^ expected u64, found u32
     
    error[E0308]: mismatched types
       --> src/backend/metal/src/factory.rs:570:36
        |
    570 |                             width: w as u32,
        |                                    ^^^^^^^^ expected u64, found u32
     
    error[E0308]: mismatched types
       --> src/backend/metal/src/factory.rs:571:37
        |
    571 |                             height: h as u32,
        |                                     ^^^^^^^^ expected u64, found u32
     
    error[E0308]: mismatched types
       --> src/backend/metal/src/factory.rs:580:36
        |
    580 |                             width: w as u32,
        |                                    ^^^^^^^^ expected u64, found u32
     
    error[E0308]: mismatched types
       --> src/backend/metal/src/factory.rs:581:37
        |
    581 |                             height: h as u32,
        |                                     ^^^^^^^^ expected u64, found u32
     
    error[E0308]: mismatched types
       --> src/backend/metal/src/factory.rs:582:36
        |
    582 |                             depth: d as u32,
        |                                    ^^^^^^^^ expected u64, found u32
     
    error[E0308]: mismatched types
       --> src/backend/metal/src/factory.rs:590:36
        |
    590 |                             width: w as u32,
        |                                    ^^^^^^^^ expected u64, found u32
     
    error[E0308]: mismatched types
       --> src/backend/metal/src/factory.rs:591:37
        |
    591 |                             height: h as u32,
        |                                     ^^^^^^^^ expected u64, found u32
     
    error[E0308]: mismatched types
       --> src/backend/metal/src/factory.rs:592:36
        |
    592 |                             depth: d as u32,
        |                                    ^^^^^^^^ expected u64, found u32
     
    error: aborting due to 12 previous errors
     
    error: Could not compile `gfx_device_metal`.
     
    To learn more, run the command again with --verbose. 
```

**Comment by msiglreith** [comment]
Oh, I had to use overrides to make it compile on my machine, probably interface for these functions changed and I didn't override with the exact same crate version.

**Comment by kvark** [comment]
Actually, Travis complains about the same things: https://travis-ci.org/gfx-rs/gfx/jobs/255680748#L1836

**Comment by msiglreith** [comment]
Looks like everything is green besides nightlies.

Using `D32_S8` for metal now due to lack of `D24_S8` support it seems. How to handle pixel formats seems to be an open issue as neither vulkan nor metal require vendors to support at least one *specific*  depth stencil format.
The metal swapchain also doesn't create the [ds textures](https://github.com/msiglreith/gfx/blob/pr_asteria_35/src/window/metal/src/lib.rs#L226) for the backbuffers as I don't know how to implement (cc @JohnColanduoni) and can't test it anyway (so not much use in trying heh).

**Comment by JohnColanduoni** [comment]
@msiglreith Metal always supports D32/D32_S8, and supports D24_S8 on some desktop cards (this is orthogonal to Metal feature sets for whatever reason, and there's a separate function on MTLDevice for checking for D24 support specifically). Depth texture creation for render targets is the same as Vulkan/DX, you can just create a separate texture with the desired pixel format and be good to go. I'll give it a shot this week if I can.

**Comment by msiglreith** [comment]
@JohnColanduoni Ah right, D32_S8 is actually supported everywhere on metal.
Concerning the depth stencil images: Is there some special handling for swapchain images? If you can look into it this would be great!

**Comment by JohnColanduoni** [comment]
@msiglreith No, you can take any suitable texture and put it into an MTLRenderPassDescriptor. Everything should be fine as long as the dimensions/samples/etc. match.

**Pull request merged**
