### PR TITLE
[gl] Set blend per attachment

### PR DESCRIPTION
**Pull request by grovesNL**
Sets blend per attachments. I haven't added caching yet because I wanted to verify whether this is the correct approach.

### CODE REVIEW

**Comment by grovesNL** [comment]
If blend isn't specified for an attachment, should we keep the previously bound blend state or revert to a default state (like `ColorBlendDesc::EMPTY` or the OpenGL default)? Or should we require that blend is specified for all attachments?

**Comment by kvark** [comment]
@grovesNL IIRC, it has to be specified for all attachments

**Comment by grovesNL** [comment]
Sounds good. We can add an assertion that blend is specified for all attachments later (if it doesn't already exist somewhere).

I updated my commit to add a cache (untested until the GL backend is slightly more usable) although it seems a bit ugly because of the nested `Option`. I guess we could share some of this logic when we cache more attachment state.

**Comment by kvark** [comment]
thanks @grovesNL !
bors r=msiglreith

**Pull request merged**
