### PR TITLE
Fixed warning about unecessary parenthesis

### PR DESCRIPTION
**Pull request by bvssvni**

### CODE REVIEW

**Comment by bvssvni** [comment]
@homu +r

**Comment by bvssvni** [comment]
Seems that homu is not working with my user.

**Comment by bvssvni** [comment]
I also noticed that the core is 0.7.0 https://github.com/gfx-rs/gfx/blob/master/src/core/Cargo.toml#L17. The v0.7 branch is 0.7.2, so is crates.io https://crates.io/crates/gfx.

**Comment by kvark** [comment]
@homu r+

**Comment by csherratt** [comment]
@homu retry

**Comment by csherratt** [comment]
@homu retry

**Pull request merged**
