### PR TITLE
[WIP] Metal Backend

### PR DESCRIPTION
**Pull request by fkaa**
#### Done:
* `gfx_window_metal`
* Metal backend in `gfx_app`
* PSO
* Reflection
* Texture/Samplers
* Command buffer/encoder
* Depth/stencil things

#### Almost done:
* Bunch of factory methods for updating data etc.

#### Not started:
* Instancing
* Fixing memory leaks – the thing i'm looking forward to the least (i'm saving `.retain()`, `.release()` for last)

Probably bunch of other stuff i missed mentioning, but should crop up eventually

### CODE REVIEW

**Comment by fkaa** [comment]
We have clear color now 🔨 

clear

**Comment by bvssvni** [comment]
Can you rebase? I want to try it on my computer.

**Comment by fkaa** [comment]
@bvssvni that should do it! (Only the cube example "works" at the moment though)

**Comment by bvssvni** [comment]
I'm getting this error:

```
src/backend/metal/src/command.rs:68:1: 68:30 error: the trait `Copy` may not be implemented for this type; variant `SetViewport` does not implement `Copy` [E0205]
src/backend/metal/src/command.rs:68 #[derive(Clone, Copy, Debug)]
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by fkaa** [comment]
Sorry, was working with local cargo override. Pushed the changes now.

**Comment by bvssvni** [comment]
@fkaa Still getting same error.

**Comment by fkaa** [comment]
`cargo update -p metal`?

**Comment by bvssvni** [comment]
@fkaa Yay! It works!

**Comment by fkaa** [comment]
We have cube!
cube

**Comment by kvark** [comment]
Thanks @fkaa! Proceeding with merge.
The biggest problem here would be supporting the code base, given that it grows faster than our contributor base.

**Comment by kvark** [comment]
@homu r+

**Comment by kvark** [comment]
@fkaa was able to get the shadow example kinda working with some tweaking:
shadow example
The backend is not ready for adoption, but it's getting close to it!

**Pull request merged**
