### PR TITLE
[mtl] impl create_surface() the way vulkan backend did

### PR DESCRIPTION
**Pull request by Michael-Lfx**
Fixes #issue
PR checklist:
- [x] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [x] tested examples with the following backends:
  - [x] metal
- [x] `rustfmt` run on changed code

### CODE REVIEW

**Comment by aleksijuvani** [comment]
This removes the public functions `create_surface_from_uiview` and `create_surface_from_nsview` which makes window creation significantly more difficult when the winit feature is disabled. Only the `create_surface_from_layer` function remains. Was this intentional?

**Comment by Michael-Lfx** [comment]
Yes. Both iOS and macOS supports `CAMetalLayer` and has almost the same operation. If you are not using `winit` I think you are using `MTLView` or rewriting `+ layerClass` to change the underlaying layer to `CAMetalLayer`. In such case `create_surface_from_layer()` can be called without any problem, right?

**Comment by aleksijuvani** [comment]
If I wanted to use `create_surface_from_layer` with an `NSView`, I think I would have to duplicate all the logic that already exists in `create_from_nsview`. At least I think that's the case? I see that it checks for an existing `CAMetalLayer` on the `NSView`, but creates it if it doesn't exist. When does the layer not exist exactly?

To be more specific about what I'm doing, I'm trying to create a surface from an `NSView` handle I get from winit (and winit only provides an `NSView`), but I'm using a version of winit (eventloop-2.0 specifically) than the one used by gfx-hal, so I cannot use the winit feature in gfx-hal. Additionally, disabling the winit feature allows me to be more agnostic about the windowing library I'm using, so I can easily switch it out in the future.

**Comment by kvark** [comment]
I missed the fact it removes the entry points, sorry!
At the end of the day, everyone should just be providing a layer to us to use. But this time has not yet come, and we'll need to expose the entry points for longer.

**Pull request merged**
