### PR TITLE
Add missing 'Debug's

### PR DESCRIPTION
**Pull request by omni-viral**
Fixes #issue
PR checklist:
- [ ] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [ ] tested examples with the following backends:
- [ ] `rustfmt` run on changed code

---
This change is [Reviewable](https://reviewable.io/reviews/gfx-rs/gfx/2459)

### CODE REVIEW

**Comment by omni-viral** [comment]
As usual :)
But I can't build dx and vulkan.
So would be cool if someone will fix those

**Comment by kvark** [comment]
@omni-viral wait, what? You can't build Vulkan?

**Comment by omni-viral** [comment]
@kvark I can't build `gfx-backend-vulkan` or `gfx-backend-dx12`

**Comment by kvark** [comment]
You moved on MacOS? I thought you like Vulkan :)

**Comment by MaikKlein** [comment]
I would happily accept a PR and publish `0.24.5`. The current version of ash also doesn't implement `Debug`. 

What do you want to see in the debug output? The addresses of all the function pointers?

**Pull request merged**
