### PR TITLE
gl: skip presentation sync if sync isn't available

### PR DESCRIPTION
**Pull request by grovesNL**
Sibling to #3463 for `master`

### CODE REVIEW

**Comment by grovesNL** [comment]
Actually still working on this, looks like we can't use the change from 0.6 directly

**Comment by grovesNL** [comment]
Should be ok now

**Review by kvark — APPROVED** [review]
Thank you!
bors r+

**Comment by kvark** [comment]
bors retry

**Comment by grovesNL** [comment]
bors retry

**Comment by grovesNL** [comment]
Not sure what's happening here, bors is failing with:
```erlang
{:badmatch,
  {:error, :push, 422,
   "{\"message\":\"3 of 8 required status checks are in progress.\",\"documentation_url\":\"https://docs.github.com/articles/about-protected-branches\"}"}},
 [
   {BorsNG.Worker.Batcher, :complete_batch, 3,
    [file: 'lib/worker/batcher.ex', line: 707]},
   {BorsNG.Worker.Batcher, :maybe_complete_batch, 1,
    [file: 'lib/worker/batcher.ex', line: 653]},
   {BorsNG.Worker.Batcher, :handle_cast, 2,
    [file: 'lib/worker/batcher.ex', line: 92]},
   {:gen_server, :try_dispatch, 4,
    [file: 'gen_server.erl', line: 637]},
   {:gen_server, :handle_msg, 6,
    [file: 'gen_server.erl', line: 711]},
   {:proc_lib, :init_p_do_apply, 3,
    [file: 'proc_lib.erl', line: 249]}
 ]}
```

bors r=kvark

**Comment by grovesNL** [comment]
With the new egl surface handling, I don't think this is needed anymore

**Pull request closed without merging**
