### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by bvssvni**

### CODE REVIEW

**Comment by bvssvni** [comment]
The tests are failing because a dependency conflict. I've updated Cargo.toml in gfx_meta, but it still fails.

**Comment by csherratt** [comment]
Looks like you overlooked glutin in the dev_dependencies. It's still at 0.3. That should fix the build.

**Comment by bvssvni** [comment]
What is the problem with genmesh here?

**Comment by csherratt** [comment]
I fixed genmesh. But it looks like we did the same mistake here. Always fix your dependencies.

**Comment by csherratt** [comment]
@homu r+

Do you have publish rights @bvssvni or do you need someone else to publish it for you?

**Comment by bvssvni** [comment]
@csherratt I have publish rights to gfx_window_glutin. Will publish when this gets merged.

**Comment by csherratt** [comment]
Thanks @bvssvni

**Pull request merged**
