### PR TITLE
subbuffer-barrier

### PR DESCRIPTION
**Pull request by omni-viral**
Fixes #issue
PR checklist:
- [ ] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [ ] tested examples with the following backends:
- [ ] `rustfmt` run on changed code

---
This change is [Reviewable](https://reviewable.io/reviews/gfx-rs/gfx/2505)

### CODE REVIEW

**Comment by msiglreith** [comment]
not sure about this one, unable to support it at least on dx12.

**Comment by omni-viral** [comment]
@msiglreith if I understand something in barriers you always can specify more than you need.

**Comment by msiglreith** [comment]
@omni-viral I believe it legal to use a subrange of a buffer as storage buffer for example and other subrange as index buffer without interference. This would most likely cause issues with dx12 as inferes flushes and invalidations via resource state transitions, which apply to the whole resource Vulkan is a bit closer to the hardware which makes it difficult to map such more fine granular use cases to other backends ):
In practice, it might work okish or we would need to fallback to whole pipeline flushes in this case, not totally sure.

**Comment by kvark** [comment]
I agree this may be problematic on D3D12, but it's already in Vulkan so with this API change we'll get less info lost in portability-gfx translation, so it's good to merge.

**Pull request merged**
