### PR TITLE
Update gfx_window_glfw dependencies

### PR DESCRIPTION
**Pull request by bvssvni**
- Bumped to 0.7.0

### CODE REVIEW

**Comment by kvark** [comment]
@bvssvni I believe you also need to fix the root Cargo.toml for the proper gfx_window_glfw version

**Comment by bvssvni** [comment]
@kvark Thanks!

**Comment by bvssvni** [comment]
Something is wrong:

```
$ RUST_BACKTRACE=1 cargo test
   Compiling gfx_meta v0.0.1 (file:///Users/sven/rust/gfx-rs)
examples/performance/main.rs:80:31: 80:42 error: mismatched types:
 expected `&mut glfw::Window`,
    found `&mut glfw::Window`
(expected struct `glfw::Window`,
    found a different struct `glfw::Window`) [E0308]
examples/performance/main.rs:80         gfx_window_glfw::init(&mut window);
                                                              ^~~~~~~~~~~
examples/performance/main.rs:80:31: 80:42 help: run `rustc --explain E0308` to see a detailed explanation
examples/performance/main.rs:80:31: 80:42 note: Perhaps two different versions of crate `glfw` are being used?
examples/performance/main.rs:80         gfx_window_glfw::init(&mut window);
                                                              ^~~~~~~~~~~
examples/cube/main.rs:66:31: 66:42 error: mismatched types:
 expected `&mut glfw::Window`,
    found `&mut glfw::Window`
(expected struct `glfw::Window`,
    found a different struct `glfw::Window`) [E0308]
examples/cube/main.rs:66         gfx_window_glfw::init(&mut window);
                                                       ^~~~~~~~~~~
examples/cube/main.rs:66:31: 66:42 help: run `rustc --explain E0308` to see a detailed explanation
examples/cube/main.rs:66:31: 66:42 note: Perhaps two different versions of crate `glfw` are being used?
examples/cube/main.rs:66         gfx_window_glfw::init(&mut window);
                                                       ^~~~~~~~~~~
error: aborting due to previous error
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330
stack backtrace:
   1:        0x11172df68 - sys::backtrace::tracing::imp::write::h1201e57c6294fe34meu
   2:        0x111735265 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42633
   3:        0x111734d67 - panicking::default_handler::hf05ebe6f5051398d7uy
   4:        0x1116fdc46 - sys_common::unwind::begin_unwind_inner::h4982b28b47fc4af3Edt
   5:        0x1116fe73e - sys_common::unwind::begin_unwind_fmt::hd376940858ab4d15Kct
   6:        0x11172ba97 - rust_begin_unwind
   7:        0x1117751d0 - panicking::panic_fmt::h1951bd5aee0da5596YL
   8:        0x111775dcc - panicking::panic::hdd3a73762ff915d4DXL
   9:        0x10e311650 - mir::tcx::LvalueTy<'tcx>::projection_ty::hbec9c71badfdb444Dap
  10:        0x10e311bb4 - mir::tcx::Mir<'tcx>::lvalue_ty::heb6788f7a9b6ed34aip
  11:        0x10dd20e22 - trans::collector::MirNeighborCollector<'a, 'tcx>.MirVisitor<'tcx>::visit_lvalue::hd11a6aa6acc8cd8cJTR
  12:        0x10dd1ceb4 - trans::collector::collect_items_rec::h3dc009fb1aec2856oER
  13:        0x10dd1d15d - trans::collector::collect_items_rec::h3dc009fb1aec2856oER
  14:        0x10dd1d15d - trans::collector::collect_items_rec::h3dc009fb1aec2856oER
  15:        0x10dc5956e - trans::base::collect_translation_items::_$u7b$$u7b$closure$u7d$$u7d$::closure.61541
  16:        0x10dc42ef0 - trans::base::trans_crate::h531c175a837e50a9V7k
  17:        0x10d2e1ba2 - driver::phase_4_translate_to_llvm::h3afc9db8b10ef6ba60a
  18:        0x10d2e04ef - driver::compile_input::_$u7b$$u7b$closure$u7d$$u7d$::closure.28625
  19:        0x10d2dbf3d - driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::closure.27655
  20:        0x10d2d552f - middle::ty::context::ctxt<'tcx>::create_and_enter::h16370449639472876456
  21:        0x10d2d15d6 - driver::phase_3_run_analysis_passes::h5853511246890233426
  22:        0x10d2a4e15 - driver::compile_input::h27df3d6ee04221f3Bca
  23:        0x10d295622 - run_compiler::h38b6440e1875c9dbQGc
  24:        0x10d292af5 - sys_common::unwind::try::try_fn::h17241262537369473458
  25:        0x11172ba2b - __rust_try
  26:        0x111723db3 - sys_common::unwind::inner_try::h32fed9e41dabff9fGat
  27:        0x10d2933a9 - boxed::F.FnBox<A>::call_box::h4352742376966607717
  28:        0x11173425f - sys::thread::Thread::new::thread_start::haf91877606a2ed5dyJx
  29:     0x7fff877e5898 - _pthread_body
  30:     0x7fff877e5729 - _pthread_start

Could not compile `gfx_meta`.
```

Seems to be using gfx_window_glfw 0.7.0 version in Cargo.lock.

**Comment by kvark** [comment]
@bvssvni I think you are missing the fix in `[dev_dependencies]` in the root `Cargo.toml`

**Comment by kvark** [comment]
Thanks!

**Pull request merged**
