### PR TITLE
Texture compression pre-ll -> v0.18

### PR DESCRIPTION
**Pull request by alexheretic**
This change merges in pre-ll changes into v0.18, as the simplest method of getting BCn texture format & glutin 0.21 support there released.

Includes
* #2684
* #2722 
* #2734
* #2745 
* #2742
* #2736
* #2733

The addition of the BC1 & BC3 texture `SurfaceType`s is technically a breaking change for gfx_core, this change instead treats it as a non-breaking change taking the view that it will only break the `gfx_device_*` backends which can be updated and released alongside.

Version bumps:
* gfx_core `0.9` -> `0.9.1`
* gfx_device_gl `0.16` -> `0.16.1`
* gfx_device_dx11 `0.8.1` -> `0.8.2`
* gfx `0.18` -> `0.18.1`
* gfx_window_dxgi `0.19` -> `0.19.1`
* gfx_window_glfw `0.17` -> `0.17.1`
* gfx_window_glutin `0.30` -> `0.31`
* gfx_window_sdl `0.9` -> `0.9.1`

**All** these crates should be released to prevent external breakage.

Alternatively if it's desired to treat the changes as an external breakage this pr should be closed in favour of planning the release of v0.19.

### CODE REVIEW

**Comment by kvark** [comment]
Alright, no objections/feedback from other members. Let's continue.
bors r+

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
>curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect

bors retry

**Comment by kvark** [comment]
uh, I suppose we should try later

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
@alexheretic all the things are published now. Crossing fingers for no breakages. :crossed_fingers: 
Thank you for all the great work updating pre-ll and adding support for compressed textures! :clap: :medal_military:

**Comment by alexheretic** [comment]
Nice one. Thanks @kvark @msiglreith for reviewing these changes. I can switch the game back to v0.18 releases now.

**Pull request merged**
