### PR TITLE
[0.1/dx12] typeless image format

### PR DESCRIPTION
**Pull request by kvark**
sibling of #2664 for hal-0.1 branch

### CODE REVIEW

**Comment by msiglreith** [comment]
Dou you want to bump the version already or add further fixes beforehand? I assume the reset behavior changes and support for concurrent recording will be needed for wgpu anyway.

**Comment by kvark** [comment]
The version is bumped here, I thought you'd fix the reset behavior at some point. Should I address this myself instead?

**Comment by msiglreith** [comment]
> I thought you'd fix the reset behavior at some point

Sure give me a few minutes. I won't address the recording stuff for now

**Comment by kvark** [comment]
bors r=msiglreith

**Pull request merged**
