### PR TITLE
GL Image refactor

### PR DESCRIPTION
**Pull request by kvark**
We haven't been taking care of the backend, so I'm trying to catch up a bit. This PR aligns the `use` sections to the other backends, fixes creation of image views and refactors them internally. Finally, it removes `glutin` code altogether.
cc @zicklag

### CODE REVIEW

**Comment by zicklag** [comment]
Yay! So we can get rid of all of the WGL code then too right? Also, are we going to want move this commit over to the hal-0.6 branch too?

I figure to create that PR I'll be cherry-picking my GL commits plus the ones in this branch, though probably wait for this to merge right?

**Comment by kvark** [comment]
@zicklag please rebase your upcoming 0.6 changes on top of #3455

**Comment by zicklag** [comment]
OK, it's up at #3457.

**Review by grovesNL — APPROVED** [review]
bors r+

**Pull request merged**
