### PR TITLE
Replace time with std::time

### PR DESCRIPTION
**Pull request by serprex**

### CODE REVIEW

**Comment by kvark** [comment]
ping! the skybox example doesn't compile with this change (look at the Travis log)

**Comment by serprex** [comment]
Fixed now. Sorry for commit spam; not on my home dev machine

**Comment by kvark** [comment]
Thanks! Do you mind if I squash it?

**Comment by serprex** [comment]
Please do

**Comment by kvark** [comment]
Ok, just waiting for AppVeyor...

**Comment by kvark** [comment]
Thanks!

**Pull request merged**
