### PR TITLE
[master/dx11] Increase max bound descriptor set count

### PR DESCRIPTION
**Pull request by cwfitzgerald**
Rolls up #3487 now that wgpu is targeting master! Should be the last major rollup I need to do! Woooo!

I looked at #3449 again but I don't think master needs that change, it looks correct.

### CODE REVIEW

**Review by kvark — APPROVED** [review]
bors r+

**Comment by kvark** [comment]
bors retry

**Comment by cwfitzgerald** [comment]
bors retry

**Comment by kvark** [comment]
bors retry

**Pull request merged**
