### PR TITLE
Add note about `examples` directory

### PR DESCRIPTION
**Pull request by grovesNL**
Add note about switching `cwd` to `examples` to further clarify the comment in the code block.

### CODE REVIEW

**Comment by kvark** [comment]
bors retry

**Comment by grovesNL** [comment]
bors r=kvark

**Comment by grovesNL** [comment]
@kvark is it because AppVeyor needs to report to bors unconditionally or something (even if AppVeyor skips this because it doesn't see a diff)?

**Comment by kvark** [comment]
Time to drop appveyor? :)

**Comment by grovesNL** [comment]
If there are no concerns about #2451 then I think we could try it out and see how it goes. @msiglreith what do you think?

**Pull request closed without merging**
