### PR TITLE
Added `clear_raw()` methods to Encoder (squashed version of #2193).

### PR DESCRIPTION
**Pull request by icefoxen**
See #2193 for details.

kvark you monster you made me figure out how to use `git squash` again.  :-P

Which apparently got git confused enough to require a new branch.

### CODE REVIEW

**Comment by kvark** [comment]
@icefoxen you shouldn't have needed a new branch. Let's talk some day about git ;)
But the code looks good, thank you!
bors r+

**Comment by kvark** [comment]
hmm. Why is it canceled?..
bors r+

**Comment by ZeGentzy** [comment]
@kvark @icefoxen Looks to be canceled again. Maybe try resubmitting this PR.

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
bors delegate+
(plz don't forget r=me instead of r+)

**Comment by icefoxen** [comment]
bors r=me

**Comment by kvark** [comment]
It looks like the failure is sort of legitimate?.. caused by the lack of documentation in macros module, on Nightly only.
@icefoxen could you rebase on latest, so that we can see if it will fix it?
I recently merged https://github.com/gfx-rs/gfx/pull/2545, and it was fine on CI

**Comment by jojolepro** [comment]
Hello. Any idea when this will be merged? It appears some changes in the repository that were done before the 0.17.3 release of gfx-rs are not included in the crates.io version. I'm hoping the next gfx_core (and gfx opengl device) release will contain those changes.

Thanks!

**Comment by kvark** [comment]
Rebased now, let's try once more.
bors r+

**Comment by kvark** [comment]
Added some comments to the macros, to unbreak nightly builds.
bors r+

**Comment by kvark** [comment]
Trouble here is that AppVeyor is already disconnected from the repo as a whole, but pre-ll build system still uses it :(
bors r+

**Comment by kvark** [comment]
Maybe I need to re-open the PR in order to get rid of AppVeyor...

**Pull request merged**
