### PR TITLE
Made Buffer only able to hold Copyable types.

### PR DESCRIPTION
**Pull request by Binero**
Title says it all.

### CODE REVIEW

**Comment by kvark** [comment]
That adds a little bit of code for the constraints everywhere. So while this specific case is fine, I wonder if this is a good direction in general. Like, should we also constraint `T: format::RenderFormat` in `handle::RenderTargetView`? This would add much more code noise, and then other handles would need to be constrained as well. In the end, will it give us much?

**Comment by Binero** [comment]
It'll add noise only on generic code. Most people actually using the Buffers will know what `T` is, so they don't need to worry about adding an annoying `+ Copy`.

**Comment by kvark** [comment]
Yes, and there is a lot of generic code inside gfx itself, plus whatever user abstracts over us.
What is the real benefit though? Just for the sake of self-documented code?

**Comment by Binero** [comment]
Indeed. Just for the sake of self-documented code.

**Comment by kvark** [comment]
Team, what do you think? @cmr @csherratt @bvssvni @fkaa

**Comment by bvssvni** [comment]
I like to put constraints on methods when possible, not on struct declarations.

**Comment by Binero** [comment]
I would agree with that if there was any way to create such a structure where the restraint wasn't there. But the restraint has to be there for the object to even exist.

**Comment by kvark** [comment]
@Binero But you are never creating  structure in isolation, right? If you are using it, you'll get the compile error anyway. The only hypothetical use-case that is not ideal is if you declare the buffer with some parameter but never use it.

**Comment by Binero** [comment]
Sure. My argument is for self-documenting code. It seems yours is just for short code. I'd prefer the first, but I get the counter argument.

**Comment by kvark** [comment]
It looks like the Rust team is following the same scheme as well. Look at the `HashMap` for example:
http://doc.rust-lang.org/std/collections/struct.HashMap.html

It doesn't restrict the type, even though the implementation only works with stuff that has `Eq` and `Hash`, obviously.
I suppose this is convincing enough. Closing.

**Pull request closed without merging**
