### PR TITLE
feat: Increase maximum number of vertex buffers in a descriptor

### PR DESCRIPTION
**Pull request by Rhuagh**
This change is [Reviewable](https://reviewable.io/reviews/gfx-rs/gfx/1750)

### CODE REVIEW

**Comment by Rhuagh** [comment]
I hope that was the correct branch to do the PR against :)

**Comment by kvark** [comment]
Thanks!
bors r+

**Comment by kvark** [comment]
Bors r+

**Comment by torkleyy** [comment]
I think it doesn't work when the first letter is an uppercase "B".

**Comment by kvark** [comment]
It is supposed to work with capital B

**Comment by torkleyy** [comment]
Hm, didn't know that. It's taking pretty long though.

**Comment by msiglreith** [comment]
It will start once the other PRs are finished, which are currently running.

**Pull request merged**
