### PR TITLE
[0.6/dx11] Fix Dynamic Offsets with Command List Emulation

### PR DESCRIPTION
**Pull request by cwfitzgerald**
This fixes a bug the shadow example had on non-nvidia platforms.

### CODE REVIEW

**Review by grovesNL — APPROVED** [review]

**Comment by kvark** [comment]
bors r=grovesNL,kvark

**Comment by cwfitzgerald** [comment]
bors retry

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
argh
bors retry

**Pull request merged**
