### PR TITLE
feat: Update winit to 0.10

### PR DESCRIPTION
**Pull request by Rhuagh**
Builds on all backends, not tested on any backends due to blocked by bugs and/or lack of supported devices.

---
This change is [Reviewable](https://reviewable.io/reviews/gfx-rs/gfx/1759)

### CODE REVIEW

**Comment by kvark** [comment]
This seem to miss some commits?

**Comment by Rhuagh** [comment]
Better now?

**Comment by Rhuagh** [comment]
Tested DX12 now, works after applying the fix from @msiglreith

**Comment by kvark** [comment]
Well that was trivial :)
Thank you!
bors r+

**Comment by Rhuagh** [comment]
Gnh

**Pull request merged**
