### PR TITLE
[ll] Clear attachments and small fixes

### PR DESCRIPTION
**Pull request by msiglreith**
* Add `clear_attachments` command for clears inside renderpasses
* dx12: Implement `Reset` command
* dx12: Fix subresource ranges for image transitions

### CODE REVIEW

**Comment by kvark** [comment]
Looks like DX12 build is broken too?..

**Comment by msiglreith** [comment]
Latest `spirv_cross` versions `0.1.x` were breaking backwards compatibility. Should be fixed again with the changes from #1526

**Pull request merged**
