### PR TITLE
Update .travis.yml to use a newer version of cmake

### PR DESCRIPTION
**Pull request by eugene2k**
This fixes the glfw issue. xcb is unsolved for now.

### CODE REVIEW

**Comment by msiglreith** [comment]
Do we still need the `xcb` crate dependency? #1016 moved all the xcb related window creation to winit. So we might be able to drop it completley.

**Comment by kvark** [comment]
`winit` doesn't support `xcb`, it only uses `xlib` on linux. So we still need `xcb` for systems that don't sport `xlib`, even if behind a feature gate.

**Comment by kvark** [comment]
could you rebase please?

**Comment by eugene2k** [comment]
Rebased. And having a WTH moment here. xcb compiles wiithout complaints now, it seems...

**Comment by kvark** [comment]
@homu r+

**Pull request merged**
