### PR TITLE
Update to glutin 0.8, Winit 0.6

### PR DESCRIPTION
**Pull request by csherratt**
This will require gfx_window_glutin to be published.

I'm on linux and didn't get a chance to test the trianglell example.

### CODE REVIEW

**Comment by kvark** [comment]
Looks great! One small thing - gfx_app version also needs a bump.

**Comment by kvark** [comment]
I wonder, where did travis go?..

**Comment by kvark** [comment]
@homu r+

**Comment by kvark** [comment]
@homu r+

**Comment by kvark** [comment]
Almost there! OSX just needs a fixup.

**Comment by kvark** [comment]
@homu r+

**Comment by kvark** [comment]
Woohoo!

**Comment by ishitatsuyuki** [comment]
May I ask it to be published?

**Comment by kvark** [comment]
@ishitatsuyuki I can publish `gfx_window_glutin` later tonight. Do you need any other crates among the updated ones?

**Comment by ishitatsuyuki** [comment]
I only need the glutin one. Thanks!

**Comment by kvark** [comment]
@ishitatsuyuki ok, will do. Please use an override to a locally-checked-out crate in the meantime

**Comment by kvark** [comment]
@ishitatsuyuki version 0.16.0 is published now from rev https://github.com/gfx-rs/gfx/commit/162221c9de84107130bef51f3c9cc0b7574ee75b

**Pull request merged**
