### PR TITLE
[hal-0.2] Back-port Debug implementations

### PR DESCRIPTION
**Pull request by kvark**
Sibling of #2787 
cc @BourgondAries 
PR checklist:
- [x] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [ ] tested examples with the following backends:
- [ ] `rustfmt` run on changed code

### CODE REVIEW

**Comment by Michael-Lfx** [comment]
Will it increase the binary size when adding `derive Debug` to these struct?

**Comment by m4b** [comment]
> Will it increase the binary size when adding `derive Debug` to these struct?

yes

**Comment by Michael-Lfx** [comment]
Can we use to conditional compilation to remove them to get a small binary package? It's good to keep our app small both on AppStore and Google Play.

**Comment by m4b** [comment]
> Can we use to conditional compilation to remove them to get a small binary package? It's good to keep our app small both on AppStore and Google Play.

Debug print functions (which will account for the increased binary size) will only be included in binary if they're used (if you link with `--gc-sections`) so I wouldn't worry about it.

**Pull request merged**
