### PR TITLE
Basic Android / GLES support

### LINKED ISSUE #160: Add Android support
@dobkeratops have a good example in https://github.com/dobkeratops/android_rust_gl

We'll probably need a platform implemented as well as to have a separate GLES-2.0 device.

### PR DESCRIPTION
**Pull request by kvark**
Closes #160 (basic support, more fixes might be needed later on)

Note: a side effect of this PR is a requirement of GL-3.2 for the example launcher. Glutin needs to be augmented in order to make this more flexible. GFX itself can still work with GL-2.1 though.

Image from @ozkriff:
Android triangle

### CODE REVIEW

**Comment by csherratt** [comment]
LGTM

**Comment by kvark** [comment]
To make this more complete, we need GLES support to `gfx_app`, so that the examples (or at least some of them) could be run out of the box.

**Comment by fkaa** [comment]
@kvark does it require a new backend or can it run on the OpenGL one with `Capabilities` restricting it to GLES features?

**Comment by kvark** [comment]
No, it's the same backend, fortunately :)

**Comment by kvark** [comment]
Ok, I got the cube example working with the example launcher without any modifications now. I consider Android/ES done, at least for now. Feel free to add more features in other PRs!

**Comment by kvark** [comment]
@csherratt review again please?

**Comment by csherratt** [comment]
Looks good! This looks ready to merge, if there is anything else I can put hold off.

**Comment by kvark** [comment]
@homu r+

**Comment by csherratt** [comment]
@homu r+

**Pull request merged**
