### PR TITLE
Update spirv_cross to 0.12.1

### PR DESCRIPTION
**Pull request by zakorgy**
PR checklist:
- [x] `make` succeeds (on *nix)
- [x] `make reftests` succeeds
- [x] tested examples with the following backends:
  - Vulkan
  - DX12
- [ ] `rustfmt` run on changed code

---
This change is [Reviewable](https://reviewable.io/reviews/gfx-rs/gfx/2584)

### CODE REVIEW

**Comment by grovesNL** [comment]
It seemed to timeout on Windows after (or while) creating cache
bors retry

**Comment by kvark** [comment]
I don't see any related settings to play with in Travis UI.
bors retry

**Comment by kvark** [comment]
bors r=grovesNL

**Comment by kvark** [comment]
If it doesn't pass, please rebase (so that we can have that travis config update)

**Pull request merged**
