### PR TITLE
[gl] Texture border capability

### PR DESCRIPTION
**Pull request by kvark**
needed for Emscripten support

### CODE REVIEW

**Comment by kvark** [comment]
bors r=msiglreith

**Comment by msiglreith** [comment]
Sry, missed to readd you.. not sure why it worked for `gfx/portability` but not here out of the box
bors r+

**Comment by msiglreith** [comment]
bors r-
Canceling as it will probably timeout again. So time to add a `bors.toml` to increase the timeout..

**Comment by msiglreith** [comment]
hm
bors r+

**Comment by kvark** [comment]
bors r=msiglreith

**Pull request merged**
