### PR TITLE
Rename Adapter methods to match conventions

### PR DESCRIPTION
**Pull request by torkleyy**
Not sure if you care about this stuff.

### CODE REVIEW

**Comment by kvark** [comment]
Thank you!
bors r+

**Comment by torkleyy** [comment]
Should I do the same for other traits?

**Comment by kvark** [comment]
Yes, but please also link to the convention.

**Comment by torkleyy** [comment]
This is the RFC: https://github.com/rust-lang/rfcs/blob/master/text/0344-conventions-galore.md#gettersetter-apis

**Pull request merged**
